name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew app:assembleDebug

      - name: Find APK path
        run: find app/build/outputs -type f

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: momo-auto-reply-apk
          path: |
            **/outputs/**/*.apk
